// Terms & Conditions page for Currio
// Route: /terms-conditions
import React from "react";
import Link from "next/link";

export const metadata = {
	title: "Terms & Conditions | Currio",
	description: "Currio Terms & Conditions - Rules and guidelines for using our AI-powered course generation platform.",
};

export default function TermsConditionsPage() {
	return (
		<main className="mx-auto max-w-3xl px-4 py-8 sm:py-12 bg-white min-h-screen">
			<nav className="mb-6 border-b border-gray-200" aria-label="Site">
				<div className="py-3 flex items-center justify-between">
					<Link href="/" className="font-serif font-bold text-xl tracking-tight text-gray-900">
						Currio
					</Link>
					<Link href="/" className="text-sm text-blue-600 hover:underline">
						Return Home
					</Link>
				</div>
			</nav>
			<article className="text-gray-800 leading-relaxed">
				<header className="mb-8">
					<h1 className="text-3xl sm:text-4xl font-serif font-bold tracking-tight mb-4 text-[#1A1A1A]">
						Terms &amp; Conditions
					</h1>
					<p className="text-gray-500 text-sm">
						<strong>Last Updated:</strong> <em>December 31, 2025</em>
					</p>
					<p className="mt-6 text-lg text-gray-600">
						Welcome to <strong>Currio</strong> (&quot;we,&quot; &quot;us,&quot; &quot;our,&quot; &quot;the Service&quot;). By accessing or using our AI-powered course generation platform, you (&quot;you,&quot; &quot;user&quot;) agree to these Terms &amp; Conditions (&quot;Terms&quot;). Please read them carefully. If you do not agree, do not use Currio.
					</p>
				</header>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">1. Acceptance of Terms</h2>
					<p className="text-gray-700 mb-4">
						By creating an account or using Currio, you acknowledge that you have read, understood, and agree to be bound by these Terms, as well as our <Link href="/privacy-policy" className="text-blue-600 hover:underline">Privacy Policy</Link>. If you do not agree to these Terms, you must discontinue use of the Service immediately.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">2. Service Description</h2>
					<p className="text-gray-700 mb-4">
						Currio is an AI-powered educational platform that generates personalized courses, quizzes, flashcards, and audio podcasts based on user prompts. The Service utilizes third-party AI models (Google Gemini, OpenAI) and public domain resources (Wikimedia Commons) to create educational content.
					</p>
					<div className="bg-blue-50 p-4 rounded-lg border border-blue-200 mt-4">
						<p className="text-sm text-blue-800">
							<strong>Note:</strong> All content generated by Currio is AI-generated and may contain inaccuracies. Currio is a study aid and not a substitute for formal education, professional advice, or primary source materials.
						</p>
					</div>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">3. User Accounts &amp; Eligibility</h2>
					
					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">3.1 Account Creation</h3>
					<p className="text-gray-700 mb-4">
						To access certain features, you must create an account using Google Firebase Authentication. You agree to:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Provide accurate and complete information</li>
						<li>Maintain the security of your account credentials</li>
						<li>Notify us immediately of any unauthorized access</li>
						<li>Accept responsibility for all activities under your account</li>
					</ul>

					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">3.2 Eligibility</h3>
					<p className="text-gray-700 mb-4">
						You must be at least 13 years old to use Currio. If you are under 18, you must have parental or guardian consent. By using Currio, you represent that you meet these age requirements.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">4. Course Content &amp; Sharing</h2>
					
					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">4.1 Private by Default</h3>
					<p className="text-gray-700 mb-4">
						All courses you generate are <strong>private by default</strong>. Only you can view and access your private courses.
					</p>

					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">4.2 Public Sharing</h3>
					<p className="text-gray-700 mb-4">
						You may choose to make your courses public using the &quot;Make Public&quot; toggle. By making a course public, you grant Currio and other users a non-exclusive, worldwide, royalty-free license to:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Display your course in the public &quot;Explore&quot; feed</li>
						<li>Allow other users to view and learn from your course</li>
						<li>Index your course for search engines</li>
						<li>Associate your display name with the course as its creator</li>
					</ul>

					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">4.3 Content Guidelines</h3>
					<p className="text-gray-700 mb-4">
						You agree not to generate or share courses that:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Contain illegal, harmful, or offensive content</li>
						<li>Violate intellectual property rights</li>
						<li>Include private, sensitive, or confidential information</li>
						<li>Promote violence, discrimination, or harassment</li>
						<li>Contain spam, malware, or malicious links</li>
						<li>Violate academic integrity policies</li>
					</ul>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">5. Academic Integrity &amp; Proper Use</h2>
					<p className="text-gray-700 mb-4">
						Currio is designed to support learning—not replace it. You agree to use Currio ethically and responsibly:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li><strong>Prohibited Uses:</strong> You may not use Currio for cheating, academic misconduct, plagiarism, or circumventing institutional policies</li>
						<li><strong>Study Aid Only:</strong> Currio is a supplementary learning tool, not a replacement for coursework, textbooks, or lectures</li>
						<li><strong>Verification Required:</strong> Always verify AI-generated content with authoritative sources before relying on it for important decisions</li>
					</ul>
					<p className="text-gray-700 mb-4">
						We reserve the right to suspend or terminate accounts that misuse the platform for academic dishonesty.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">6. AI-Generated Content Disclaimer</h2>
					<div className="bg-gray-50 p-6 rounded-xl border border-gray-100">
						<p className="text-gray-700 mb-4">
							<strong>Important:</strong> Currio uses Large Language Models (LLMs) and automated systems to generate content. You acknowledge and accept that:
						</p>
						<ul className="list-disc pl-6 space-y-2 text-gray-700 text-sm">
							<li><strong>Accuracy:</strong> AI may produce factually incorrect, outdated, or misleading information (&quot;hallucinations&quot;). Always verify critical information.</li>
							<li><strong>Bias:</strong> AI models may reflect biases from their training data.</li>
							<li><strong>Images:</strong> Automated image selection from Wikimedia Commons may occasionally display irrelevant or inappropriate images. We do not manually review every image.</li>
							<li><strong>No Warranties:</strong> Content is provided &quot;as is&quot; without warranties of any kind.</li>
						</ul>
					</div>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">7. Intellectual Property</h2>
					
					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">7.1 Ownership</h3>
					<p className="text-gray-700 mb-4">
						Currio and its original content, features, and functionality are owned by Nishant Das and are protected by international copyright, trademark, and other intellectual property laws.
					</p>

					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">7.2 User-Generated Content</h3>
					<p className="text-gray-700 mb-4">
						You retain ownership of your prompts and private courses. However, for public courses, you grant Currio a perpetual, irrevocable, worldwide license to display and distribute the content.
					</p>

					<h3 className="text-xl font-bold mt-6 mb-3 text-[#1A1A1A]">7.3 Copyright Infringement</h3>
					<p className="text-gray-700 mb-4">
						If you believe content on Currio infringes your copyright, please contact us at <a href="mailto:dasbudhe@gmail.com" className="text-blue-600 hover:underline">dasbudhe@gmail.com</a> with:
					</p>
					<ol className="list-decimal pl-6 space-y-1 text-gray-700 mb-4">
						<li>Identification of the copyrighted work</li>
						<li>Location of the infringing content (URL)</li>
						<li>Your contact information</li>
						<li>A statement of good faith belief that use is unauthorized</li>
						<li>Your physical or electronic signature</li>
					</ol>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">8. Third-Party Services &amp; Links</h2>
					<p className="text-gray-700 mb-4">
						Currio integrates with third-party services including Google Gemini, OpenAI, Firebase, Upstash Redis, and Wikimedia Commons. We are not responsible for:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Service availability, downtime, or errors from third-party providers</li>
						<li>Data handling practices of external services (see our Privacy Policy)</li>
						<li>Content or accuracy of external links</li>
					</ul>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">9. Limitation of Liability</h2>
					<p className="text-gray-700 mb-4">
						<strong>To the maximum extent permitted by law:</strong>
					</p>
					<ul className="list-disc pl-6 space-y-2 text-gray-700 mb-4">
						<li>Currio is provided &quot;as is&quot; without warranties of any kind</li>
						<li>We are not liable for any indirect, incidental, special, consequential, or punitive damages</li>
						<li>We are not responsible for data loss, academic consequences, or reliance on AI-generated content</li>
						<li>Our total liability shall not exceed the amount you paid us in the past 12 months</li>
						<li>We are not liable for offense, emotional distress, or harm caused by automated image selection or AI-generated content</li>
					</ul>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">10. Indemnification</h2>
					<p className="text-gray-700 mb-4">
						You agree to indemnify, defend, and hold harmless Currio and Nishant Das from any claims, damages, liabilities, losses, or expenses arising from:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Your use or misuse of the Service</li>
						<li>Violation of these Terms or applicable laws</li>
						<li>Infringement of third-party rights</li>
						<li>Your prompts, courses, or content you share</li>
						<li>Academic integrity violations</li>
					</ul>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">11. Data Security &amp; Loss</h2>
					<p className="text-gray-700 mb-4">
						While we implement reasonable security measures, we cannot guarantee absolute security. You acknowledge that:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Data loss, corruption, or unauthorized access may occur</li>
						<li>You should maintain backups of important information</li>
						<li>Service interruptions may happen without notice</li>
						<li>We are not responsible for data loss or service outages</li>
					</ul>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">12. Account Termination</h2>
					<p className="text-gray-700 mb-4">
						We reserve the right to suspend or terminate your account at any time if you:
					</p>
					<ul className="list-disc pl-6 space-y-1 text-gray-700 mb-4">
						<li>Violate these Terms</li>
						<li>Engage in fraudulent or abusive behavior</li>
						<li>Misuse the platform for academic dishonesty</li>
						<li>Create harmful or illegal content</li>
					</ul>
					<p className="text-gray-700 mb-4">
						You may delete your account at any time. Upon account deletion, your private courses may be deleted, but public courses may be anonymized and retained for the community.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">13. Governing Law &amp; Dispute Resolution</h2>
					<p className="text-gray-700 mb-4">
						These Terms are governed by the laws of <strong>India</strong>. Any disputes arising from or related to the use of Currio shall be resolved exclusively in the courts of <strong>Guwahati, India</strong>.
					</p>
					<p className="text-gray-700 mb-4">
						You agree to first attempt to resolve disputes informally by contacting us before initiating any legal proceedings.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">14. Changes to Terms</h2>
					<p className="text-gray-700 mb-4">
						We reserve the right to modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of Currio after changes constitutes acceptance of the updated Terms.
					</p>
					<p className="text-gray-700 mb-4">
						We encourage you to review these Terms periodically. Material changes will be communicated via email or platform notification.
					</p>
				</section>

				<hr className="my-8 border-gray-200" />

				<section>
					<h2 className="text-2xl font-serif font-semibold mt-8 mb-4 text-[#1A1A1A]">15. Contact Information</h2>
					<p className="text-gray-700 mb-4">
						For questions, concerns, or support regarding these Terms, please contact:
					</p>
					<div className="mt-4 mb-8">
						<p className="font-semibold text-gray-900">Nishant Das</p>
						<p className="text-gray-700">Developer, Currio</p>
						<a href="mailto:dasbudhe@gmail.com" className="text-blue-600 hover:text-blue-800 hover:underline transition-colors">
							dasbudhe@gmail.com
						</a>
					</div>
				</section>
				
				<div className="mt-12 pt-8 border-t border-gray-100 text-center text-gray-400 text-sm">
					&copy; {new Date().getFullYear()} Currio. All rights reserved.
				</div>
			</article>
		</main>
	);
}
